server:
  port: 5555

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
      - id: routes
      uri: https://localhost
      predicates:
      - Cookie=mycookie,mycookievalue     