version: '3.1'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://db/aluraforum?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
services:

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: aluraforum      
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    volumes:
    - forum_volume:/var/lib/mysql
    networks:
      - backend
  
  aluraforum:
    image: fernandobezerra/aluraforum
    depends_on:
    - db
    ports:
    - 8080:8080
    environment:
      <<: *database-variables
    networks:
    - backend
  
volumes:
  forum_volume:
  
networks:
  backend: